/* ================================================
   Mock Data Store - MediCare+ Doctor Appointment System
   ================================================ */

const MockData = (() => {

  /* ── Hospital Info ── */
  const hospital = {
    id: 'HOSP001',
    name: 'MediCare+',
    fullName: 'MediCare+ Multi-Specialty Hospital',
    tagline: 'Your Health, Our Priority',
    address: '42, Rajiv Gandhi Salai, Sholinganallur, Chennai - 600119, Tamil Nadu',
    phone: '+91 44 6789 0123',
    emergency: '+91 98765 43210',
    email: 'care@medicarePlus.in',
    website: 'www.medicareplus.in',
    established: 2008,
    beds: 450,
    accreditation: 'NABH Accredited',
    timings: 'OPD: Mon–Sat, 8:00 AM – 8:00 PM | Emergency: 24×7',
    logo: '🏥',
    socialLinks: {
      facebook: '#',
      twitter: '#',
      instagram: '#',
      linkedin: '#',
    },
  };

  /* ── Departments ── */
  const departments = [
    {
      id: 'DEPT001',
      name: 'Cardiology',
      head: 'Dr. Ramesh Iyer',
      beds: 60,
      description: 'Comprehensive cardiac care including interventional cardiology, heart surgery, and rehabilitation.',
      icon: '❤️',
    },
    {
      id: 'DEPT002',
      name: 'Neurology',
      head: 'Dr. Priya Venkataraman',
      beds: 45,
      description: 'Advanced neuro diagnostics and treatment for stroke, epilepsy, Parkinson\'s, and more.',
      icon: '🧠',
    },
    {
      id: 'DEPT003',
      name: 'Orthopedics',
      head: 'Dr. Suresh Balaji',
      beds: 80,
      description: 'Joint replacement, sports medicine, spine surgery, and trauma care.',
      icon: '🦴',
    },
  ];

  /* ── Specialties ── */
  const specialties = [
    { id: 'SP001', name: 'Cardiology',       icon: '❤️',  color: '#ec4899', bg: 'rgba(236, 72, 153, 0.12)', doctorCount: 3, description: 'Heart & cardiovascular care' },
    { id: 'SP002', name: 'Neurology',        icon: '🧠',  color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.12)', doctorCount: 2, description: 'Brain & nervous system' },
    { id: 'SP003', name: 'Orthopedics',      icon: '🦴',  color: '#ec4899', bg: 'rgba(236, 72, 153, 0.12)', doctorCount: 2, description: 'Bones, joints & muscles' },
    { id: 'SP004', name: 'Pediatrics',       icon: '👶',  color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.12)', doctorCount: 3, description: 'Child health & development' },
    { id: 'SP005', name: 'Gynecology',       icon: '🌸',  color: '#ec4899', bg: 'rgba(236, 72, 153, 0.12)', doctorCount: 2, description: "Women's health & maternity" },
    { id: 'SP006', name: 'Dermatology',      icon: '🧴',  color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.12)', doctorCount: 2, description: 'Skin, hair & nail care' },
    { id: 'SP007', name: 'Ophthalmology',    icon: '👁️',  color: '#ec4899', bg: 'rgba(236, 72, 153, 0.12)', doctorCount: 1, description: 'Eye care & vision' },
    { id: 'SP008', name: 'General Medicine', icon: '💊',  color: '#8b5cf6', bg: 'rgba(139, 92, 246, 0.12)', doctorCount: 3, description: 'Primary & preventive care' },
  ];

  /* ── Doctors (8) ── */
  const doctors = [
    {
      id: 'DOC001',
      name: 'Dr. Ramesh Iyer',
      specialty: 'Cardiology',
      specialtyId: 'SP001',
      qualification: 'MBBS, MD (Cardiology), DM, FACC',
      experience: 18,
      rating: 4.9,
      reviewCount: 312,
      fee: 1500,
      gender: 'Male',
      languages: ['Tamil', 'English', 'Hindi'],
      photo: null,
      initials: 'RI',
      bio: 'Senior Interventional Cardiologist with 18+ years specializing in complex coronary interventions, heart failure management, and preventive cardiology.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-19',
      availability: {
        Monday:    ['09:00', '09:30', '10:00', '10:30', '11:00', '14:00', '14:30', '15:00'],
        Wednesday: ['09:00', '09:30', '10:00', '11:00', '15:00', '15:30', '16:00'],
        Friday:    ['09:00', '09:30', '10:30', '11:00', '11:30', '14:00', '14:30'],
      },
      achievements: ['Best Cardiologist Award 2023', 'NABH Certified', '5000+ Surgeries'],
      consultationType: ['In-person', 'Video'],
    },
    {
      id: 'DOC002',
      name: 'Dr. Priya Venkataraman',
      specialty: 'Neurology',
      specialtyId: 'SP002',
      qualification: 'MBBS, MD (Medicine), DM (Neurology)',
      experience: 14,
      rating: 4.8,
      reviewCount: 215,
      fee: 1800,
      gender: 'Female',
      languages: ['Tamil', 'English'],
      photo: null,
      initials: 'PV',
      bio: 'Expert Neurologist specializing in epilepsy, stroke management, movement disorders, and neuro-rehabilitation.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-20',
      availability: {
        Tuesday:   ['10:00', '10:30', '11:00', '11:30', '15:00', '15:30'],
        Thursday:  ['09:30', '10:00', '10:30', '14:00', '14:30', '15:00'],
        Saturday:  ['09:00', '09:30', '10:00', '11:00'],
      },
      achievements: ['Stroke Excellence Award 2022', 'Published 40+ Research Papers'],
      consultationType: ['In-person', 'Video'],
    },
    {
      id: 'DOC003',
      name: 'Dr. Suresh Balaji',
      specialty: 'Orthopedics',
      specialtyId: 'SP003',
      qualification: 'MBBS, MS (Ortho), FRCS',
      experience: 22,
      rating: 4.7,
      reviewCount: 428,
      fee: 1200,
      gender: 'Male',
      languages: ['Tamil', 'English', 'Telugu'],
      photo: null,
      initials: 'SB',
      bio: 'Leading Orthopedic Surgeon with expertise in joint replacement, arthroscopic surgery, and spine disorders. Over 3000 successful surgeries.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-19',
      availability: {
        Monday:    ['09:00', '09:30', '10:00', '10:30', '11:00'],
        Wednesday: ['14:00', '14:30', '15:00', '15:30', '16:00'],
        Friday:    ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'],
      },
      achievements: ['Best Ortho Surgeon TN 2021', 'Minimally Invasive Surgery Expert'],
      consultationType: ['In-person'],
    },
    {
      id: 'DOC004',
      name: 'Dr. Ananya Krishnamurthy',
      specialty: 'Pediatrics',
      specialtyId: 'SP004',
      qualification: 'MBBS, MD (Pediatrics), DCH',
      experience: 11,
      rating: 4.9,
      reviewCount: 567,
      fee: 800,
      gender: 'Female',
      languages: ['Tamil', 'English', 'Kannada'],
      photo: null,
      initials: 'AK',
      bio: 'Compassionate Pediatrician with special interest in neonatal care, child nutrition, vaccinations, and developmental pediatrics.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-18',
      availability: {
        Monday:    ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00'],
        Tuesday:   ['09:00', '09:30', '10:00', '14:00', '14:30'],
        Thursday:  ['09:00', '09:30', '10:00', '10:30', '11:00'],
        Saturday:  ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'],
      },
      achievements: ['Best Pediatrician Tamil Nadu 2023', 'Child Welfare Champion'],
      consultationType: ['In-person', 'Video', 'Chat'],
    },
    {
      id: 'DOC005',
      name: 'Dr. Meenakshi Sundaram',
      specialty: 'Gynecology',
      specialtyId: 'SP005',
      qualification: 'MBBS, MS (Obstetrics & Gynecology), FRCOG',
      experience: 16,
      rating: 4.8,
      reviewCount: 389,
      fee: 1000,
      gender: 'Female',
      languages: ['Tamil', 'English'],
      photo: null,
      initials: 'MS',
      bio: 'Senior Gynecologist specializing in high-risk pregnancies, laparoscopic surgery, PCOS management, and infertility treatments.',
      hospitalId: 'HOSP001',
      available: false,
      nextAvailable: '2026-08-22',
      availability: {
        Tuesday:   ['09:00', '09:30', '10:00', '10:30', '14:00', '14:30'],
        Thursday:  ['09:00', '09:30', '10:00', '11:00', '11:30'],
        Saturday:  ['09:00', '09:30', '10:00', '10:30', '11:00'],
      },
      achievements: ['10,000+ Deliveries', 'High-Risk Pregnancy Expert'],
      consultationType: ['In-person'],
    },
    {
      id: 'DOC006',
      name: 'Dr. Arjun Chandrasekhar',
      specialty: 'Dermatology',
      specialtyId: 'SP006',
      qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
      experience: 9,
      rating: 4.6,
      reviewCount: 198,
      fee: 900,
      gender: 'Male',
      languages: ['Tamil', 'English', 'Malayalam'],
      photo: null,
      initials: 'AC',
      bio: 'Expert Dermatologist specializing in cosmetic dermatology, acne, psoriasis, hair loss treatments, and laser therapies.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-19',
      availability: {
        Monday:    ['10:00', '10:30', '11:00', '11:30', '15:00', '15:30'],
        Wednesday: ['09:30', '10:00', '10:30', '11:00', '14:00', '14:30'],
        Friday:    ['10:00', '10:30', '11:00', '11:30', '14:00'],
      },
      achievements: ['Cosmetic Dermatology Certified', 'Laser Treatment Expert'],
      consultationType: ['In-person', 'Video'],
    },
    {
      id: 'DOC007',
      name: 'Dr. Lakshmi Narayanan',
      specialty: 'Ophthalmology',
      specialtyId: 'SP007',
      qualification: 'MBBS, MS (Ophthalmology), DOMS',
      experience: 20,
      rating: 4.8,
      reviewCount: 287,
      fee: 700,
      gender: 'Female',
      languages: ['Tamil', 'English'],
      photo: null,
      initials: 'LN',
      bio: 'Senior Ophthalmologist with 20 years of experience in cataract surgery, glaucoma management, LASIK, and retinal disorders.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-20',
      availability: {
        Tuesday:   ['09:00', '09:30', '10:00', '10:30', '11:00', '14:00'],
        Thursday:  ['09:00', '09:30', '10:00', '11:00', '11:30'],
        Saturday:  ['09:00', '09:30', '10:00', '10:30'],
      },
      achievements: ['5000+ Cataract Surgeries', 'LASIK Pioneer Chennai'],
      consultationType: ['In-person'],
    },
    {
      id: 'DOC008',
      name: 'Dr. Karthik Rajan',
      specialty: 'General Medicine',
      specialtyId: 'SP008',
      qualification: 'MBBS, MD (General Medicine)',
      experience: 8,
      rating: 4.5,
      reviewCount: 145,
      fee: 500,
      gender: 'Male',
      languages: ['Tamil', 'English', 'Hindi'],
      photo: null,
      initials: 'KR',
      bio: 'General Physician providing comprehensive primary care including preventive health check-ups, chronic disease management, and acute illness treatment.',
      hospitalId: 'HOSP001',
      available: true,
      nextAvailable: '2026-08-18',
      availability: {
        Monday:    ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00', '15:30'],
        Tuesday:   ['09:00', '09:30', '10:00', '10:30', '11:00', '14:00', '14:30'],
        Wednesday: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'],
        Thursday:  ['09:00', '09:30', '10:00', '14:00', '14:30', '15:00'],
        Friday:    ['09:00', '09:30', '10:00', '10:30', '11:00', '14:00'],
      },
      achievements: ['Most Accessible Doctor Award', '3000+ Patients Served'],
      consultationType: ['In-person', 'Video', 'Chat'],
    },
  ];

  /* ── Patients (5) ── */
  const patients = [
    {
      id: 'PAT001',
      name: 'Arjun Sharma',
      age: 34,
      gender: 'Male',
      dob: '1992-03-15',
      bloodGroup: 'O+',
      phone: '+91 98412 56789',
      email: 'arjun.sharma@gmail.com',
      address: '14, Anna Nagar East, Chennai - 600102',
      allergies: ['Penicillin'],
      chronicConditions: ['Mild Hypertension'],
      emergencyContact: { name: 'Sunita Sharma', relation: 'Wife', phone: '+91 98412 11111' },
      registeredOn: '2024-06-10',
      photo: null,
      initials: 'AS',
    },
    {
      id: 'PAT002',
      name: 'Kavitha Murugan',
      age: 28,
      gender: 'Female',
      dob: '1998-07-22',
      bloodGroup: 'B+',
      phone: '+91 87654 32109',
      email: 'kavitha.m@yahoo.com',
      address: '7/3, T. Nagar, Chennai - 600017',
      allergies: [],
      chronicConditions: ['PCOS'],
      emergencyContact: { name: 'Murugan K', relation: 'Father', phone: '+91 87654 10000' },
      registeredOn: '2025-01-15',
      photo: null,
      initials: 'KM',
    },
    {
      id: 'PAT003',
      name: 'Rajan Patel',
      age: 58,
      gender: 'Male',
      dob: '1967-11-08',
      bloodGroup: 'A+',
      phone: '+91 94490 67890',
      email: 'rajan.patel@hotmail.com',
      address: '23, Velachery Main Road, Chennai - 600042',
      allergies: ['Aspirin', 'Sulfa drugs'],
      chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
      emergencyContact: { name: 'Geeta Patel', relation: 'Wife', phone: '+91 94490 22222' },
      registeredOn: '2023-09-20',
      photo: null,
      initials: 'RP',
    },
    {
      id: 'PAT004',
      name: 'Sneha Krishnan',
      age: 6,
      gender: 'Female',
      dob: '2019-05-14',
      bloodGroup: 'AB+',
      phone: '+91 99000 12345',
      email: 'krishnan.family@gmail.com',
      address: '8, Adyar, Chennai - 600020',
      allergies: ['Lactose'],
      chronicConditions: [],
      emergencyContact: { name: 'Sundar Krishnan', relation: 'Father', phone: '+91 99000 12345' },
      registeredOn: '2025-05-20',
      photo: null,
      initials: 'SK',
    },
    {
      id: 'PAT005',
      name: 'Meera Nair',
      age: 42,
      gender: 'Female',
      dob: '1984-02-28',
      bloodGroup: 'O-',
      phone: '+91 96000 54321',
      email: 'meera.nair@rediff.com',
      address: '55, Besant Nagar, Chennai - 600090',
      allergies: [],
      chronicConditions: ['Hypothyroidism', 'Migraine'],
      emergencyContact: { name: 'Vijay Nair', relation: 'Husband', phone: '+91 96000 99999' },
      registeredOn: '2024-11-03',
      photo: null,
      initials: 'MN',
    },
  ];

  /* ── Appointments (10) ── */
  const appointments = [
    {
      id: 'APT001',
      patientId: 'PAT001',
      doctorId: 'DOC001',
      date: '2026-08-22',
      time: '10:00',
      duration: 30,
      type: 'In-person',
      status: 'confirmed',
      reason: 'Chest pain and breathlessness on exertion',
      notes: 'Patient reports occasional palpitations. ECG and Echo advised.',
      fee: 1500,
      paymentStatus: 'paid',
      paymentId: 'PAY001',
      createdAt: '2026-08-15T09:30:00',
      tokenNumber: 'T-015',
    },
    {
      id: 'APT002',
      patientId: 'PAT002',
      doctorId: 'DOC005',
      date: '2026-08-25',
      time: '09:30',
      duration: 30,
      type: 'In-person',
      status: 'pending',
      reason: 'Irregular menstrual cycle follow-up',
      notes: '',
      fee: 1000,
      paymentStatus: 'pending',
      paymentId: null,
      createdAt: '2026-08-17T14:00:00',
      tokenNumber: 'T-003',
    },
    {
      id: 'APT003',
      patientId: 'PAT003',
      doctorId: 'DOC008',
      date: '2026-08-18',
      time: '11:00',
      duration: 30,
      type: 'In-person',
      status: 'confirmed',
      reason: 'Diabetes routine check-up and prescription renewal',
      notes: 'HbA1c and fasting glucose test required. BP monitoring.',
      fee: 500,
      paymentStatus: 'paid',
      paymentId: 'PAY002',
      createdAt: '2026-08-10T10:15:00',
      tokenNumber: 'T-009',
    },
    {
      id: 'APT004',
      patientId: 'PAT001',
      doctorId: 'DOC001',
      date: '2026-07-30',
      time: '09:00',
      duration: 30,
      type: 'In-person',
      status: 'completed',
      reason: 'Initial consultation - hypertension evaluation',
      notes: 'Started on amlodipine 5mg. Advised low-sodium diet and daily walks.',
      fee: 1500,
      paymentStatus: 'paid',
      paymentId: 'PAY003',
      createdAt: '2026-07-25T11:00:00',
      tokenNumber: 'T-007',
      prescription: 'PRES001',
    },
    {
      id: 'APT005',
      patientId: 'PAT004',
      doctorId: 'DOC004',
      date: '2026-08-20',
      time: '10:30',
      duration: 20,
      type: 'In-person',
      status: 'confirmed',
      reason: 'Vaccination - 6 year booster shots',
      notes: 'MMR, DPT booster scheduled.',
      fee: 800,
      paymentStatus: 'paid',
      paymentId: 'PAY004',
      createdAt: '2026-08-12T08:45:00',
      tokenNumber: 'T-011',
    },
    {
      id: 'APT006',
      patientId: 'PAT002',
      doctorId: 'DOC006',
      date: '2026-08-10',
      time: '10:00',
      duration: 30,
      type: 'Video',
      status: 'completed',
      reason: 'Acne treatment review',
      notes: 'Switched from adapalene to tretinoin 0.05%. Added oral doxycycline for 6 weeks.',
      fee: 900,
      paymentStatus: 'paid',
      paymentId: 'PAY005',
      createdAt: '2026-08-05T16:20:00',
      tokenNumber: 'V-004',
      prescription: 'PRES002',
    },
    {
      id: 'APT007',
      patientId: 'PAT005',
      doctorId: 'DOC002',
      date: '2026-08-05',
      time: '15:00',
      duration: 45,
      type: 'In-person',
      status: 'completed',
      reason: 'Recurrent migraine evaluation',
      notes: 'MRI Brain ordered. Started prophylactic propranolol 40mg. Lifestyle modifications advised.',
      fee: 1800,
      paymentStatus: 'paid',
      paymentId: 'PAY006',
      createdAt: '2026-07-30T13:00:00',
      tokenNumber: 'T-021',
      prescription: 'PRES003',
    },
    {
      id: 'APT008',
      patientId: 'PAT003',
      doctorId: 'DOC003',
      date: '2026-07-15',
      time: '14:00',
      duration: 30,
      type: 'In-person',
      status: 'cancelled',
      reason: 'Knee pain evaluation',
      notes: 'Cancelled by patient - out of station.',
      fee: 1200,
      paymentStatus: 'refunded',
      paymentId: 'PAY007',
      createdAt: '2026-07-10T09:00:00',
      tokenNumber: 'T-014',
      cancelledBy: 'patient',
      cancelReason: 'Out of station',
    },
    {
      id: 'APT009',
      patientId: 'PAT005',
      doctorId: 'DOC008',
      date: '2026-08-28',
      time: '09:00',
      duration: 30,
      type: 'Video',
      status: 'confirmed',
      reason: 'Thyroid follow-up and medicine adjustment',
      notes: '',
      fee: 500,
      paymentStatus: 'paid',
      paymentId: 'PAY008',
      createdAt: '2026-08-16T17:30:00',
      tokenNumber: 'V-009',
    },
    {
      id: 'APT010',
      patientId: 'PAT001',
      doctorId: 'DOC007',
      date: '2026-09-02',
      time: '09:30',
      duration: 30,
      type: 'In-person',
      status: 'pending',
      reason: 'Annual eye examination and glasses prescription update',
      notes: '',
      fee: 700,
      paymentStatus: 'pending',
      paymentId: null,
      createdAt: '2026-08-18T10:00:00',
      tokenNumber: 'T-002',
    },
  ];

  /* ── Payments (5) ── */
  const payments = [
    { id: 'PAY001', appointmentId: 'APT001', patientId: 'PAT001', amount: 1500, status: 'success', method: 'UPI', transactionId: 'TXN20260815093012', date: '2026-08-15', gateway: 'Razorpay' },
    { id: 'PAY002', appointmentId: 'APT003', patientId: 'PAT003', amount: 500,  status: 'success', method: 'Net Banking', transactionId: 'TXN20260810101534', date: '2026-08-10', gateway: 'Razorpay' },
    { id: 'PAY003', appointmentId: 'APT004', patientId: 'PAT001', amount: 1500, status: 'success', method: 'Credit Card', transactionId: 'TXN20260725110023', date: '2026-07-25', gateway: 'Razorpay' },
    { id: 'PAY004', appointmentId: 'APT005', patientId: 'PAT004', amount: 800,  status: 'success', method: 'UPI', transactionId: 'TXN20260812084521', date: '2026-08-12', gateway: 'Razorpay' },
    { id: 'PAY005', appointmentId: 'APT006', patientId: 'PAT002', amount: 900,  status: 'success', method: 'Debit Card', transactionId: 'TXN20260805162001', date: '2026-08-05', gateway: 'Razorpay' },
    { id: 'PAY006', appointmentId: 'APT007', patientId: 'PAT005', amount: 1800, status: 'success', method: 'UPI', transactionId: 'TXN20260730130045', date: '2026-07-30', gateway: 'Razorpay' },
    { id: 'PAY007', appointmentId: 'APT008', patientId: 'PAT003', amount: 1200, status: 'refunded', method: 'UPI', transactionId: 'TXN20260710090012', date: '2026-07-10', gateway: 'Razorpay', refundId: 'REF2026071001' },
    { id: 'PAY008', appointmentId: 'APT009', patientId: 'PAT005', amount: 500,  status: 'success', method: 'Wallet', transactionId: 'TXN20260816173023', date: '2026-08-16', gateway: 'Razorpay' },
  ];

  /* ── Prescriptions (3) ── */
  const prescriptions = [
    {
      id: 'PRES001',
      appointmentId: 'APT004',
      doctorId: 'DOC001',
      patientId: 'PAT001',
      date: '2026-07-30',
      diagnosis: 'Stage 1 Hypertension',
      medicines: [
        { name: 'Amlodipine', dosage: '5mg', frequency: 'Once daily (morning)', duration: '90 days', instructions: 'Take with water, do not crush' },
        { name: 'Telmisartan', dosage: '40mg', frequency: 'Once daily (morning)', duration: '90 days', instructions: 'Can be taken with or without food' },
      ],
      advice: 'Low-sodium diet. Daily 30-min walk. Avoid alcohol. Monitor BP twice daily. Review after 3 months.',
      followUp: '2026-10-30',
      digitalSignature: 'Dr. Ramesh Iyer | Reg No: TN-MCI-12345',
    },
    {
      id: 'PRES002',
      appointmentId: 'APT006',
      doctorId: 'DOC006',
      patientId: 'PAT002',
      date: '2026-08-10',
      diagnosis: 'Moderate Acne Vulgaris',
      medicines: [
        { name: 'Tretinoin', dosage: '0.05% Cream', frequency: 'At night (after cleansing)', duration: '90 days', instructions: 'Apply pea-sized amount. Avoid sun exposure.' },
        { name: 'Doxycycline', dosage: '100mg', frequency: 'Twice daily', duration: '42 days', instructions: 'Take with a full glass of water. Avoid dairy 2 hours before/after.' },
        { name: 'Clindamycin + Nicotinamide Gel', dosage: '1%', frequency: 'Twice daily', duration: '60 days', instructions: 'Apply thin layer on affected areas morning and evening.' },
      ],
      advice: 'Use non-comedogenic sunscreen SPF 50+. Gentle face wash twice daily. Avoid picking/squeezing.',
      followUp: '2026-10-10',
      digitalSignature: 'Dr. Arjun Chandrasekhar | Reg No: TN-MCI-56789',
    },
    {
      id: 'PRES003',
      appointmentId: 'APT007',
      doctorId: 'DOC002',
      patientId: 'PAT005',
      date: '2026-08-05',
      diagnosis: 'Chronic Migraine with Aura',
      medicines: [
        { name: 'Propranolol', dosage: '40mg', frequency: 'Twice daily', duration: '90 days', instructions: 'Do not stop abruptly. Monitor pulse.' },
        { name: 'Sumatriptan', dosage: '50mg', frequency: 'As needed (max 2/day)', duration: 'SOS', instructions: 'Take at migraine onset. Do not exceed 200mg/day.' },
        { name: 'Magnesium Glycinate', dosage: '400mg', frequency: 'Once daily at bedtime', duration: '90 days', instructions: 'Can cause mild GI upset initially.' },
      ],
      advice: 'Maintain migraine diary. Regular sleep schedule. Stay hydrated. Identify and avoid triggers. Limit caffeine.',
      followUp: '2026-11-05',
      digitalSignature: 'Dr. Priya Venkataraman | Reg No: TN-MCI-78901',
    },
  ];

  /* ── Medical Records (4) ── */
  const medicalRecords = [
    {
      id: 'MR001',
      patientId: 'PAT001',
      type: 'Lab Report',
      name: 'Lipid Profile & CBC',
      date: '2026-07-28',
      doctor: 'Dr. Ramesh Iyer',
      description: 'Pre-consultation bloodwork. LDL: 148 mg/dL (borderline high), HDL: 42 mg/dL, Triglycerides: 180 mg/dL.',
      fileType: 'PDF',
      fileSize: '1.2 MB',
    },
    {
      id: 'MR002',
      patientId: 'PAT001',
      type: 'ECG Report',
      name: '12-Lead ECG',
      date: '2026-07-30',
      doctor: 'Dr. Ramesh Iyer',
      description: 'Normal sinus rhythm. No ST-T changes. HR: 76 bpm.',
      fileType: 'PDF',
      fileSize: '0.8 MB',
    },
    {
      id: 'MR003',
      patientId: 'PAT005',
      type: 'MRI Report',
      name: 'MRI Brain (Without Contrast)',
      date: '2026-08-08',
      doctor: 'Dr. Priya Venkataraman',
      description: 'No space-occupying lesion. White matter changes consistent with migraine. No midline shift.',
      fileType: 'DICOM / PDF',
      fileSize: '45 MB',
    },
    {
      id: 'MR004',
      patientId: 'PAT003',
      type: 'Lab Report',
      name: 'HbA1c & Fasting Glucose',
      date: '2026-08-17',
      doctor: 'Dr. Karthik Rajan',
      description: 'HbA1c: 7.4% (controlled), Fasting Glucose: 118 mg/dL, Post-prandial: 165 mg/dL.',
      fileType: 'PDF',
      fileSize: '0.6 MB',
    },
  ];

  /* ── Notifications (8) ── */
  const notifications = [
    {
      id: 'NOTIF001',
      userId: 'PAT001',
      type: 'appointment_confirmed',
      title: 'Appointment Confirmed',
      message: 'Your appointment with Dr. Ramesh Iyer on Aug 22 at 10:00 AM is confirmed. Token: T-015.',
      read: false,
      timestamp: '2026-08-15T09:35:00',
      icon: '✅',
      color: 'green',
      link: '/appointments/APT001',
    },
    {
      id: 'NOTIF002',
      userId: 'PAT001',
      type: 'reminder',
      title: 'Appointment Tomorrow',
      message: 'Reminder: You have an appointment with Dr. Ramesh Iyer tomorrow at 10:00 AM.',
      read: false,
      timestamp: '2026-08-21T08:00:00',
      icon: '🔔',
      color: 'blue',
      link: '/appointments/APT001',
    },
    {
      id: 'NOTIF003',
      userId: 'PAT001',
      type: 'payment_success',
      title: 'Payment Successful',
      message: '₹1,500 paid successfully via UPI for Dr. Ramesh Iyer appointment. Txn: TXN20260815093012.',
      read: true,
      timestamp: '2026-08-15T09:32:00',
      icon: '💳',
      color: 'green',
      link: '/payments/PAY001',
    },
    {
      id: 'NOTIF004',
      userId: 'PAT001',
      type: 'prescription_ready',
      title: 'Prescription Available',
      message: 'Your prescription from Dr. Ramesh Iyer (July 30) is now available to download.',
      read: true,
      timestamp: '2026-07-30T11:30:00',
      icon: '💊',
      color: 'blue',
      link: '/prescriptions/PRES001',
    },
    {
      id: 'NOTIF005',
      userId: 'PAT002',
      type: 'appointment_pending',
      title: 'Booking Under Review',
      message: 'Your appointment request with Dr. Meenakshi Sundaram on Aug 25 is awaiting confirmation.',
      read: false,
      timestamp: '2026-08-17T14:05:00',
      icon: '⏳',
      color: 'orange',
      link: '/appointments/APT002',
    },
    {
      id: 'NOTIF006',
      userId: 'PAT003',
      type: 'appointment_cancelled',
      title: 'Appointment Cancelled',
      message: 'Your appointment with Dr. Suresh Balaji on July 15 has been cancelled. Refund initiated.',
      read: true,
      timestamp: '2026-07-12T10:00:00',
      icon: '❌',
      color: 'red',
      link: '/appointments/APT008',
    },
    {
      id: 'NOTIF007',
      userId: 'PAT005',
      type: 'report_uploaded',
      title: 'MRI Report Ready',
      message: 'Your MRI Brain report is ready. Dr. Priya Venkataraman has reviewed it. Click to view.',
      read: false,
      timestamp: '2026-08-09T16:00:00',
      icon: '🩻',
      color: 'purple',
      link: '/records/MR003',
    },
    {
      id: 'NOTIF008',
      userId: 'PAT004',
      type: 'vaccination_reminder',
      title: 'Vaccination Reminder',
      message: 'Sneha\'s vaccination appointment with Dr. Ananya Krishnamurthy is on Aug 20 at 10:30 AM.',
      read: false,
      timestamp: '2026-08-18T09:00:00',
      icon: '💉',
      color: 'teal',
      link: '/appointments/APT005',
    },
  ];

  /* ── Reviews (sample per doctor) ── */
  const reviews = [
    { id: 'REV001', doctorId: 'DOC001', patientId: 'PAT001', patientName: 'Arjun S.',       rating: 5, date: '2026-07-31', text: 'Dr. Iyer is extremely knowledgeable. Explained everything clearly and patiently. The diagnosis was spot on.', helpful: 12 },
    { id: 'REV002', doctorId: 'DOC001', patientId: 'PAT003', patientName: 'Rajan P.',        rating: 5, date: '2026-06-15', text: 'Best cardiologist in Chennai. Very thorough in his examination. I fully trust his advice.', helpful: 8 },
    { id: 'REV003', doctorId: 'DOC001', patientId: 'PAT005', patientName: 'Meera N.',        rating: 4, date: '2026-05-20', text: 'Very good doctor. Slight wait time but worth it. The treatment worked well.', helpful: 5 },
    { id: 'REV004', doctorId: 'DOC004', patientId: 'PAT004', patientName: 'Krishnan Family', rating: 5, date: '2026-08-01', text: 'Dr. Ananya is wonderful with kids. Sneha was scared but the doctor made her feel so comfortable. Highly recommend!', helpful: 20 },
    { id: 'REV005', doctorId: 'DOC004', patientId: 'PAT002', patientName: 'Kavitha M.',      rating: 5, date: '2026-07-10', text: 'Excellent pediatrician. Very responsive and caring. Always available for follow-up queries.', helpful: 15 },
    { id: 'REV006', doctorId: 'DOC006', patientId: 'PAT002', patientName: 'Kavitha M.',      rating: 4, date: '2026-08-11', text: 'Good consultation via video. Prescription is working. Follow-up was prompt. Would visit again.', helpful: 7 },
  ];

  /* ── Admin Users ── */
  const adminUsers = [
    { id: 'ADM001', name: 'Vijayan Pillai',    email: 'vijayan@medicareplus.in',   role: 'super_admin',  department: null,          phone: '+91 99001 11111', status: 'active', lastLogin: '2026-08-18T08:30:00' },
    { id: 'ADM002', name: 'Saranya Bose',      email: 'saranya@medicareplus.in',   role: 'admin',        department: null,          phone: '+91 99001 22222', status: 'active', lastLogin: '2026-08-18T09:15:00' },
    { id: 'ADM003', name: 'Mohan Krishnan',    email: 'mohan@medicareplus.in',     role: 'receptionist', department: 'Front Desk',  phone: '+91 99001 33333', status: 'active', lastLogin: '2026-08-18T08:00:00' },
    { id: 'ADM004', name: 'Dr. Ramesh Iyer',   email: 'ramesh.iyer@medicareplus.in', role: 'doctor',     department: 'Cardiology',  phone: '+91 99001 44444', status: 'active', lastLogin: '2026-08-17T17:00:00' },
    { id: 'ADM005', name: 'Pavithra Suresh',   email: 'pavithra@medicareplus.in',  role: 'lab_tech',     department: 'Laboratory',  phone: '+91 99001 55555', status: 'active', lastLogin: '2026-08-16T10:00:00' },
  ];

  /* ── Time Slots (9:00 AM - 5:00 PM, 30-min intervals) ── */
  const timeSlots = [
    '09:00', '09:30',
    '10:00', '10:30',
    '11:00', '11:30',
    '12:00', '12:30',
    '13:00', '13:30',
    '14:00', '14:30',
    '15:00', '15:30',
    '16:00', '16:30',
    '17:00',
  ];

  /* ── Dashboard Stats ── */
  const dashboardStats = {
    admin: {
      totalAppointments: 1284,
      todayAppointments: 47,
      totalDoctors: 8,
      totalPatients: 2156,
      totalRevenue: 1842500,
      monthlyRevenue: 142500,
      pendingAppointments: 12,
      cancelledThisMonth: 8,
      averageRating: 4.75,
      appointmentGrowth: 12.4,
      revenueGrowth: 8.7,
      patientGrowth: 15.2,
    },
    chartData: {
      weeklyAppointments: [38, 42, 35, 47, 50, 29, 15],
      weeklyLabels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      monthlyRevenue: [112000, 98000, 125000, 142500, 118000, 136000],
      monthlyLabels: ['Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
      specialtyBreakdown: {
        Cardiology: 28, Neurology: 15, Orthopedics: 18,
        Pediatrics: 22, Gynecology: 10, Dermatology: 12,
        Ophthalmology: 8, 'General Medicine': 35,
      },
    },
  };

  /* ── Public API ── */
  return {
    hospital,
    departments,
    specialties,
    doctors,
    patients,
    appointments,
    payments,
    prescriptions,
    medicalRecords,
    notifications,
    reviews,
    adminUsers,
    timeSlots,
    dashboardStats,

    /* Helpers */
    getDoctorById:      (id) => doctors.find(d => d.id === id),
    getPatientById:     (id) => patients.find(p => p.id === id),
    getAppointmentById: (id) => appointments.find(a => a.id === id),
    getDoctorsBySpecialty: (specialty) => doctors.filter(d => d.specialty === specialty),
    getAppointmentsByPatient: (patientId) => appointments.filter(a => a.patientId === patientId),
    getAppointmentsByDoctor:  (doctorId)  => appointments.filter(a => a.doctorId === doctorId),
    getNotificationsByUser:   (userId)    => notifications.filter(n => n.userId === userId),
    getReviewsByDoctor:       (doctorId)  => reviews.filter(r => r.doctorId === doctorId),
    getUnreadCount:           (userId)    => notifications.filter(n => n.userId === userId && !n.read).length,
    getUpcomingAppointments:  (patientId) => {
      const today = new Date().toISOString().split('T')[0];
      return appointments.filter(a => a.patientId === patientId && a.date >= today && a.status !== 'cancelled');
    },
    getPastAppointments: (patientId) => {
      const today = new Date().toISOString().split('T')[0];
      return appointments.filter(a => a.patientId === patientId && (a.date < today || a.status === 'completed'));
    },
  };
})();

/* Make available globally */
if (typeof module !== 'undefined') module.exports = MockData;
